
tree:
  rows:
    - { min: 0, max: 70 }
    - { min: 71, max: 130 }
    - { min: 131, max: 195 }
    - { min: 196, max: 252 }
    - { min: 253, max: 287 }
    - { min: 288, max: 340 }
    - { min: 341, max: 375 }
    - { min: 376, max: 390 }
    - { min: 391, max: 396 }
    - { min: 397, max: 398 }
    - { min: 399, max: 399 }

