patterns:

  ruler:
    template: ruler
    config:
      normal: 0x666666
      tenth: 0xFF0000
      fifth: 0x008800

  wipergb:
    template: wipe
    config:
      tick: 3
      colors: [0xff0000, 0x00ff00, 0x0000ff, 0xffCC00, 0x00ffCC, 0xCC00ff]

  wipeblack:
    template: vwipe
    config:
      tick: 100
      colors: [0x000000]
      direction: 1

  vwipergb:
    template: vwipe
    config:
      tick: 100
      colors: [0xFF0000, 0xFFAA00, 0x00FF00, 0x00FFFF, 0x0000FF, 0xFF00FF]
      direction: 1

  rainbow:
    template: rainbow
    config:
      tick: 10

  rainbowunicorn:
    template: rainbowunicorn
    config:
      repeat: 10
      tick: 100
      direction: 1

  vrainbow:
    template: vrainbow
    config:
      repeat: 1
      tick: 100
      direction: 1

  sleep500:
    template: sleep
    config:
      time: 500